export const HERO_TEXT = 'Search over millions of candidates instantly to find your next great hire';
export const UPLOAD_RESUME = 'Upload CV';
export const ADD_RESUME = "Fill Resume Details For the Candidate"
export const RESUME_FINDER = 'CV-Finder';
export const SEARCH_BY_ID = 'Search by Resume Id';
export const SEARCH_BY_CANDIDATE_NAME = 'Search by Candidate Full Name';
export const CANDIDATE_NAME = 'Candidate Name  : ';
export const JOB_TITLE = 'Job Designation   : ';
export const CURRENT_COMPANY = 'Current Company: ';
export const JOB_DESCRIPTION = 'Job Description   : ';
export const LOADING_TEXT = 'Loading...';
export const SUBMIT_TEXT = 'SUBMIT';
export const CANCEL_TEXT = 'CANCEL';
export const REQUIRED_VALIDATION = 'Please fill out the complete form, all Fields are mandatory!';
export const UPLOAD_SUCCESS_MSG = 'Resume uploaded successfully with Resume Id :';
export const ERROR_MESSAGE = 'Something went wrong!';
export const RETRIEVE_RESUME = 'Retrieve resume Details';